// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type Call struct {
	ID                int64          `json:"id"`
	UserID            int64          `json:"user_id"`
	PhoneNumber       string         `json:"phone_number"`
	RecipientContext  sql.NullString `json:"recipient_context"`
	Objective         string         `json:"objective"`
	BackgroundContext sql.NullString `json:"background_context"`
	Status            sql.NullString `json:"status"`
	CreatedAt         sql.NullTime   `json:"created_at"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
	CompletedAt       sql.NullTime   `json:"completed_at"`
}

type CallLog struct {
	ID          int64        `json:"id"`
	CallID      int64        `json:"call_id"`
	MessageType string       `json:"message_type"`
	Content     string       `json:"content"`
	Timestamp   sql.NullTime `json:"timestamp"`
}

type User struct {
	ID        int64        `json:"id"`
	Email     string       `json:"email"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}
