// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"context"
	"database/sql"
)

type Querier interface {
	CompleteCall(ctx context.Context, id int64) (Call, error)
	CreateCall(ctx context.Context, arg CreateCallParams) (Call, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCall(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetCall(ctx context.Context, id int64) (Call, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListCallsByStatus(ctx context.Context, status sql.NullString) ([]Call, error)
	ListCallsByUser(ctx context.Context, userID int64) ([]Call, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateCallStatus(ctx context.Context, arg UpdateCallStatusParams) (Call, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
